[package]
name = "input"
version = "0.1.0"
authors = ["jrovacsek <jay@rovacsek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "3.0.2"